[General]
ReportStats=false


[UdpEndpoint bridge_in]
Mode=Server
Address=172.20.0.10
Port=18560

[UdpEndpoint host_out_1]
Mode=Normal
Address=172.20.0.14
Port=18590

[UdpEndpoint host_out_2]
Mode=Normal
Address=172.20.0.11
Port=18550

